---
services:
  ark-server:
    image: indifferentbroccoli/ark-server-docker:latest
    platform: linux/amd64
    restart: unless-stopped
    container_name: ark-server
    stop_grace_period: 30s
    ports:
      - ${SERVER_PORT:-7777}:7777/udp
      - ${QUERY_PORT:-27015}:27015/udp
      - ${RCON_PORT:-27020}:27020/tcp
    env_file:
      - .env
    volumes:
      - ./steamcmd/ark:/home/steam/steamcmd/ark
